# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'reserva_1.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.



import datetime
import os
import sqlite3
import webbrowser

from bd.conectar import connectarbd
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QDate, QDateTime
from PyQt5.QtWidgets import QMessageBox, QTableWidgetItem
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4, inch, landscape, letter
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.pdfgen import canvas
from reportlab.pdfgen.canvas import Canvas
from reportlab.platypus import (Frame, Paragraph, SimpleDocTemplate, Spacer,
                                Table, TableStyle)

# from .reportlab.platypus import Image, SimpleDocTemplate

cd_reserva = 0

# pastaApp - os.path.dirname(__file__)

# resulPDF = []


class Ui_MainWindow(object ):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1070, 559)
        MainWindow.setWindowFlags(QtCore.Qt.FramelessWindowHint)
        MainWindow.setAttribute(QtCore.Qt.WA_TranslucentBackground)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(80, 30, 941, 581))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.frame = QtWidgets.QFrame(self.page)
        self.frame.setGeometry(QtCore.QRect(90, 0, 761, 501))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(0, 0, 741, 381))
        self.label.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-bottom-right-radius: 50px;\n"
"border-top-left-radius: 50px;")
        self.label.setText("")
        self.label.setObjectName("label")
        self.layoutWidget = QtWidgets.QWidget(self.frame)
        self.layoutWidget.setGeometry(QtCore.QRect(40, 120, 668, 47))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Miriam Libre")
        font.setPointSize(8)
        font.setBold(True)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color:rgb(0,0,0)")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_3.addWidget(self.label_5)
        self.comboBox = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox.setEnabled(False)
        self.comboBox.setMinimumSize(QtCore.QSize(180, 0))
        self.comboBox.setStyleSheet("border:2px solid rgba(0,0,0,0);\n"
"border-bottom-color:rgba(146,82,101,255);")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.setItemText(0, "")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.verticalLayout_3.addWidget(self.comboBox)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Miriam Libre")
        font.setPointSize(8)
        font.setBold(True)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color:rgb(0,0,0)")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_4.addWidget(self.label_6)
        self.lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit.setEnabled(False)
        self.lineEdit.setMinimumSize(QtCore.QSize(240, 0))
        self.lineEdit.setStyleSheet("border:2px solid rgba(0,0,0,0);\n"
"border-bottom-color:rgba(146,82,101,255);")
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_4.addWidget(self.lineEdit)
        self.horizontalLayout_3.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_7 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Miriam Libre")
        font.setPointSize(8)
        font.setBold(True)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color:rgb(0,0,0)")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_5.addWidget(self.label_7)
        self.txt_solicitacao = QtWidgets.QLineEdit(self.layoutWidget)
        self.txt_solicitacao.setEnabled(False)
        self.txt_solicitacao.setMinimumSize(QtCore.QSize(110, 0))
        self.txt_solicitacao.setStyleSheet("border:2px solid rgba(0,0,0,0);\n"
"border-bottom-color:rgba(146,82,101,255);")
        self.txt_solicitacao.setObjectName("txt_solicitacao")
        self.verticalLayout_5.addWidget(self.txt_solicitacao)
        self.horizontalLayout_3.addLayout(self.verticalLayout_5)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_8 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Miriam Libre")
        font.setPointSize(8)
        font.setBold(True)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color:rgb(0,0,0)")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_6.addWidget(self.label_8)
        self.txt_agenda = QtWidgets.QLineEdit(self.layoutWidget)
        self.txt_agenda.setEnabled(False)
        self.txt_agenda.setMinimumSize(QtCore.QSize(110, 0))
        self.txt_agenda.setStyleSheet("border:2px solid rgba(0,0,0,0);\n"
"border-bottom-color:rgba(146,82,101,255);")
        self.txt_agenda.setObjectName("txt_agenda")
        self.verticalLayout_6.addWidget(self.txt_agenda)
        self.horizontalLayout_3.addLayout(self.verticalLayout_6)
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(0, 0, 741, 61))
        font = QtGui.QFont()
        font.setFamily("Miriam Libre")
        font.setPointSize(12)
        font.setBold(True)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0.505682,x2:1,y2:0.477, stop:0 rgba(150, 123, 111, 219), stop:1 rgba(85, 81, 84, 226));\n"
"border-top-left-radius: 50px;\n"
"color:rgb(0,0,0)")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.layoutWidget1 = QtWidgets.QWidget(self.frame)
        self.layoutWidget1.setGeometry(QtCore.QRect(526, 179, 182, 45))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_10 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Miriam Libre")
        font.setPointSize(8)
        font.setBold(True)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("color:rgb(0,0,0)")
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_7.addWidget(self.label_10)
        self.comboBox_2 = QtWidgets.QComboBox(self.layoutWidget1)
        self.comboBox_2.setEnabled(False)
        self.comboBox_2.setMinimumSize(QtCore.QSize(180, 0))
        self.comboBox_2.setStyleSheet("border:2px solid rgba(0,0,0,0);\n"
"border-bottom-color:rgba(146,82,101,255);")
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.setItemText(0, "")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.verticalLayout_7.addWidget(self.comboBox_2)
        self.layoutWidget2 = QtWidgets.QWidget(self.frame)
        self.layoutWidget2.setGeometry(QtCore.QRect(200, 180, 132, 45))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_9 = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Miriam Libre")
        font.setPointSize(8)
        font.setBold(True)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color:rgb(0,0,0)")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.verticalLayout.addWidget(self.label_9)
        self.txt_hr_inicio = QtWidgets.QLineEdit(self.layoutWidget2)
        self.txt_hr_inicio.setEnabled(False)
        self.txt_hr_inicio.setMinimumSize(QtCore.QSize(110, 0))
        self.txt_hr_inicio.setStyleSheet("border:2px solid rgba(0,0,0,0);\n"
"border-bottom-color:rgba(146,82,101,255);")
        self.txt_hr_inicio.setObjectName("txt_hr_inicio")
        self.verticalLayout.addWidget(self.txt_hr_inicio)
        self.layoutWidget3 = QtWidgets.QWidget(self.frame)
        self.layoutWidget3.setGeometry(QtCore.QRect(360, 180, 132, 45))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget3)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_11 = QtWidgets.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setFamily("Miriam Libre")
        font.setPointSize(8)
        font.setBold(True)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("color:rgb(0,0,0)")
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_2.addWidget(self.label_11)
        self.txt_hr_fim = QtWidgets.QLineEdit(self.layoutWidget3)
        self.txt_hr_fim.setEnabled(False)
        self.txt_hr_fim.setMinimumSize(QtCore.QSize(110, 0))
        self.txt_hr_fim.setStyleSheet("border:2px solid rgba(0,0,0,0);\n"
"border-bottom-color:rgba(146,82,101,255);")
        self.txt_hr_fim.setObjectName("txt_hr_fim")
        self.verticalLayout_2.addWidget(self.txt_hr_fim)
        self.layoutWidget4 = QtWidgets.QWidget(self.frame)
        self.layoutWidget4.setGeometry(QtCore.QRect(40, 180, 112, 45))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.layoutWidget4)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_13 = QtWidgets.QLabel(self.layoutWidget4)
        font = QtGui.QFont()
        font.setFamily("Miriam Libre")
        font.setPointSize(8)
        font.setBold(True)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("color:rgb(0,0,0)")
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_8.addWidget(self.label_13)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.layoutWidget4)
        self.lineEdit_3.setEnabled(False)
        self.lineEdit_3.setMinimumSize(QtCore.QSize(110, 0))
        self.lineEdit_3.setStyleSheet("border:2px solid rgba(0,0,0,0);\n"
"border-bottom-color:rgba(146,82,101,255);")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.verticalLayout_8.addWidget(self.lineEdit_3)
        self.layoutWidget5 = QtWidgets.QWidget(self.frame)
        self.layoutWidget5.setGeometry(QtCore.QRect(390, 70, 327, 32))
        self.layoutWidget5.setObjectName("layoutWidget5")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget5)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_81 = QtWidgets.QLabel(self.layoutWidget5)
        self.label_81.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_81.setAlignment(QtCore.Qt.AlignCenter)
        self.label_81.setObjectName("label_81")
        self.horizontalLayout.addWidget(self.label_81)
        self.txt_consulta_reserva = QtWidgets.QLineEdit(self.layoutWidget5)
        self.txt_consulta_reserva.setMinimumSize(QtCore.QSize(100, 0))
        self.txt_consulta_reserva.setStyleSheet("border:2px solid rgba(0,0,0,0);\n"
"border-bottom-color:rgba(146,82,101,255);")
        self.txt_consulta_reserva.setText("")
        self.txt_consulta_reserva.setObjectName("txt_consulta_reserva")
        self.horizontalLayout.addWidget(self.txt_consulta_reserva)
        self.btn_pesquisarRsv = QtWidgets.QPushButton(self.layoutWidget5)
        self.btn_pesquisarRsv.setMinimumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        self.btn_pesquisarRsv.setFont(font)
        self.btn_pesquisarRsv.setStyleSheet("QPushButton#btn_pesquisarRsv{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682,x2:1,y2:0.477, stop:0 rgba(150, 123, 111, 219), stop:1 rgba(85, 81, 84, 226));\n"
"    color:rgba(255, 255, 255, 210);\n"
"    border-radius: 5px;\n"
"}\n"
"QPushButton#btn_pesquisarRsv:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682,x2:1,y2:0.477, stop:0 rgba(0, 123, 111, 219), stop:1 rgba(5, 81, 84, 226));\n"
"}\n"
"QPushButton#btn_pesquisarRsv:pressed{\n"
"    padding-left:5px;\n"
"    padding -top:5px;\n"
"    background-color:rgba(150, 123, 111, 255);\n"
"}")
        self.btn_pesquisarRsv.setIconSize(QtCore.QSize(24, 24))
        self.btn_pesquisarRsv.setObjectName("btn_pesquisarRsv")
        self.horizontalLayout.addWidget(self.btn_pesquisarRsv)
        self.layoutWidget6 = QtWidgets.QWidget(self.frame)
        self.layoutWidget6.setGeometry(QtCore.QRect(40, 70, 208, 34))
        self.layoutWidget6.setObjectName("layoutWidget6")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget6)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.btn_novaRsv = QtWidgets.QPushButton(self.layoutWidget6)
        self.btn_novaRsv.setMinimumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        self.btn_novaRsv.setFont(font)
        self.btn_novaRsv.setStyleSheet("QPushButton#btn_novaRsv{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682,x2:1,y2:0.477, stop:0 rgba(150, 123, 111, 219), stop:1 rgba(85, 81, 84, 226));\n"
"    color:rgba(255, 255, 255, 210);\n"
"    border-radius: 5px;\n"
"}\n"
"QPushButton#btn_novaRsv:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682,x2:1,y2:0.477, stop:0 rgba(0, 123, 111, 219), stop:1 rgba(5, 81, 84, 226));\n"
"}\n"
"QPushButton#btn_novaRsv:pressed{\n"
"    padding-left:5px;\n"
"    padding -top:5px;\n"
"    background-color:rgba(150, 123, 111, 255);\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Icons/relatorio-de-saude.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_novaRsv.setIcon(icon)
        self.btn_novaRsv.setIconSize(QtCore.QSize(24, 24))
        self.btn_novaRsv.setObjectName("btn_novaRsv")
        self.horizontalLayout_4.addWidget(self.btn_novaRsv)
        self.btn_editar = QtWidgets.QPushButton(self.layoutWidget6)
        self.btn_editar.setEnabled(False)
        self.btn_editar.setMinimumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        self.btn_editar.setFont(font)
        self.btn_editar.setStyleSheet("QPushButton#btn_editar{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682,x2:1,y2:0.477, stop:0 rgba(150, 123, 111, 219), stop:1 rgba(85, 81, 84, 226));\n"
"    color:rgba(255, 255, 255, 210);\n"
"    border-radius: 5px;\n"
"}\n"
"QPushButton#btn_editar:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682,x2:1,y2:0.477, stop:0 rgba(0, 123, 111, 219), stop:1 rgba(5, 81, 84, 226));\n"
"}\n"
"QPushButton#btn_editar:pressed{\n"
"    padding-left:5px;\n"
"    padding -top:5px;\n"
"    background-color:rgba(150, 123, 111, 255);\n"
"}")
        self.btn_editar.setIcon(icon)
        self.btn_editar.setIconSize(QtCore.QSize(24, 24))
        self.btn_editar.setObjectName("btn_editar")
        self.horizontalLayout_4.addWidget(self.btn_editar)
        self.layoutWidget7 = QtWidgets.QWidget(self.frame)
        self.layoutWidget7.setGeometry(QtCore.QRect(80, 300, 242, 34))
        self.layoutWidget7.setObjectName("layoutWidget7")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.layoutWidget7)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.btn_agendar = QtWidgets.QPushButton(self.layoutWidget7)
        self.btn_agendar.setEnabled(False)
        self.btn_agendar.setMinimumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        self.btn_agendar.setFont(font)
        self.btn_agendar.setStyleSheet("QPushButton#btn_agendar{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682,x2:1,y2:0.477, stop:0 rgba(150, 123, 111, 219), stop:1 rgba(85, 81, 84, 226));\n"
"    color:rgba(255, 255, 255, 210);\n"
"    border-radius: 5px;\n"
"}\n"
"QPushButton#btn_agendar:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682,x2:1,y2:0.477, stop:0 rgba(0, 123, 111, 219), stop:1 rgba(5, 81, 84, 226));\n"
"}\n"
"QPushButton#btn_notifica:pressed{\n"
"    padding-left:5px;\n"
"    padding -top:5px;\n"
"    background-color:rgba(150, 123, 111, 255);\n"
"}")
        self.btn_agendar.setIcon(icon)
        self.btn_agendar.setIconSize(QtCore.QSize(24, 24))
        self.btn_agendar.setObjectName("btn_agendar")
        self.horizontalLayout_5.addWidget(self.btn_agendar)
        self.btn_cancelar = QtWidgets.QPushButton(self.layoutWidget7)
        self.btn_cancelar.setMinimumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        self.btn_cancelar.setEnabled(False)
        self.btn_cancelar.setFont(font)
        self.btn_cancelar.setStyleSheet("QPushButton#btn_cancelar{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682,x2:1,y2:0.477, stop:0 rgba(150, 123, 111, 219), stop:1 rgba(85, 81, 84, 226));\n"
"    color:rgba(255, 255, 255, 210);\n"
"    border-radius: 5px;\n"
"}\n"
"QPushButton#btn_cancelar:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682,x2:1,y2:0.477, stop:0 rgba(0, 123, 111, 219), stop:1 rgba(5, 81, 84, 226));\n"
"}\n"
"QPushButton#btn_cancelar:pressed{\n"
"    padding-left:5px;\n"
"    padding -top:5px;\n"
"    background-color:rgba(150, 123, 111, 255);\n"
"}")
        self.btn_cancelar.setIcon(icon)
        self.btn_cancelar.setIconSize(QtCore.QSize(24, 24))
        self.btn_cancelar.setObjectName("btn_cancelar")
        self.horizontalLayout_5.addWidget(self.btn_cancelar)
        self.layoutWidget8 = QtWidgets.QWidget(self.frame)
        self.layoutWidget8.setGeometry(QtCore.QRect(11, 251, 713, 24))
        self.layoutWidget8.setObjectName("layoutWidget8")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget8)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_12 = QtWidgets.QLabel(self.layoutWidget8)
        font = QtGui.QFont()
        font.setFamily("Miriam Libre")
        font.setPointSize(8)
        font.setBold(True)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("color:rgb(0,0,0)")
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_2.addWidget(self.label_12)
        self.txt_obs = QtWidgets.QLineEdit(self.layoutWidget8)
        self.txt_obs.setEnabled(False)
        self.txt_obs.setMinimumSize(QtCore.QSize(640, 0))
        self.txt_obs.setMaximumSize(QtCore.QSize(640, 16777215))
        self.txt_obs.setStyleSheet("border:2px solid rgba(0,0,0,0);\n"
"border-bottom-color:rgba(146,82,101,255);")
        self.txt_obs.setObjectName("txt_obs")
        self.horizontalLayout_2.addWidget(self.txt_obs)
        self.btn_reservas = QtWidgets.QPushButton(self.frame)
        self.btn_reservas.setGeometry(QtCore.QRect(590, 300, 131, 30))
        self.btn_reservas.setMinimumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        self.btn_reservas.setFont(font)
        self.btn_reservas.setStyleSheet("QPushButton#btn_notifica{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(11, 131, 120, 219), stop:1 rgba(85, 98, 112, 226));\n"
"    color:rgba(255, 255, 255, 210);\n"
"    border-radius: 5px;\n"
"}\n"
"QPushButton#btn_notifica:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682,x2:1,y2:0.477, stop:0 rgba(150, 123, 111, 219), stop:1 rgba(85, 81, 84, 226));\n"
"}\n"
"QPushButton#btn_notifica:pressed{\n"
"    padding-left:5px;\n"
"    padding -top:5px;\n"
"    background-color:rgba(150, 123, 111, 255);\n"
"}")
        self.btn_reservas.setIcon(icon)
        self.btn_reservas.setIconSize(QtCore.QSize(24, 24))
        self.btn_reservas.setObjectName("btn_reservas")
        self.btn_sair = QtWidgets.QPushButton(self.frame)
        self.btn_sair.setGeometry(QtCore.QRect(650, 340, 51, 31))
        self.btn_sair.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        self.btn_sair.setFont(font)
        self.btn_sair.setStyleSheet("QPushButton#btn_sair{\n"
"    background-color:rgb(255,0,0);\n"
"    color:rgb(170, 255, 255);\n"
"    border-radius: 10px;\n"
"}\n"
"QPushButton#btn_sair:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682,x2:1,y2:0.477, stop:0 rgba(150, 123, 111, 219), stop:1 rgba(85, 81, 84, 226));\n"
"}\n"
"QPushButton#btn_sair:pressed{\n"
"    padding-left:5px;\n"
"    padding -top:5px;\n"
"    background-color:rgba(150, 123, 111, 255);\n"
"}\n"
"\n"
"\n"
"")
        self.btn_sair.setIcon(icon)
        self.btn_sair.setIconSize(QtCore.QSize(24, 24))
        self.btn_sair.setObjectName("btn_sair")
        self.btn_alterarR = QtWidgets.QPushButton(self.frame)
        self.btn_alterarR.setGeometry(QtCore.QRect(460, 300, 117, 32))
        self.btn_alterarR.setMinimumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        self.btn_alterarR.setEnabled(False)
        self.btn_alterarR.setFont(font)
        self.btn_alterarR.setStyleSheet("QPushButton#btn_alterarR{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682,x2:1,y2:0.477, stop:0 rgba(150, 123, 111, 219), stop:1 rgba(85, 81, 84, 226));\n"
"    color:rgba(255, 255, 255, 210);\n"
"    border-radius: 5px;\n"
"}\n"
"QPushButton#btn_alterarR:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682,x2:1,y2:0.477, stop:0 rgba(0, 123, 111, 219), stop:1 rgba(5, 81, 84, 226));\n"
"}\n"
"QPushButton#btn_alterarR:pressed{\n"
"    padding-left:5px;\n"
"    padding -top:5px;\n"
"    background-color:rgba(150, 123, 111, 255);\n"
"}")
        self.btn_alterarR.setIcon(icon)
        self.btn_alterarR.setIconSize(QtCore.QSize(24, 24))
        self.btn_alterarR.setObjectName("btn_alterarR")
        self.txt_id_reserva = QtWidgets.QLineEdit(self.frame)
        self.txt_id_reserva.setEnabled(False)
        self.txt_id_reserva.setGeometry(QtCore.QRect(290, 70, 30, 29))
        self.txt_id_reserva.setMinimumSize(QtCore.QSize(30, 0))
        self.txt_id_reserva.setMaximumSize(QtCore.QSize(30, 16777215))
        self.txt_id_reserva.setStyleSheet("border:2px solid rgba(0,0,0,0);\n"
"border-bottom-color:rgba(146,82,101,255);")
        self.txt_id_reserva.setText("")
        self.txt_id_reserva.setObjectName("txt_id_reserva")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.label_3 = QtWidgets.QLabel(self.page_2)
        self.label_3.setGeometry(QtCore.QRect(0, 0, 971, 491))
        self.label_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.frame_2 = QtWidgets.QFrame(self.page_2)
        self.frame_2.setGeometry(QtCore.QRect(0, 0, 941, 471))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.pushButton = QtWidgets.QPushButton(self.frame_2)
        self.pushButton.setGeometry(QtCore.QRect(690, 100, 75, 24))
        self.pushButton.setObjectName("pushButton")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setGeometry(QtCore.QRect(200, 100, 49, 16))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_4.setGeometry(QtCore.QRect(290, 100, 381, 22))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.tableWidget = QtWidgets.QTableWidget(self.frame_2)
        self.tableWidget.setGeometry(QtCore.QRect(40, 150, 891, 192))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(10)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(9, item)
        self.label_14 = QtWidgets.QLabel(self.frame_2)
        self.label_14.setGeometry(QtCore.QRect(300, 20, 351, 61))
        font = QtGui.QFont()
        font.setFamily("Miriam Libre")
        font.setPointSize(23)
        font.setBold(True)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("color:rgb(0,0,0)")
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_2.setGeometry(QtCore.QRect(410, 380, 75, 24))
        self.pushButton_2.setObjectName("pushButton_2")
        self.stackedWidget.addWidget(self.page_2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.btn_novaRsv, self.comboBox)
        MainWindow.setTabOrder(self.comboBox, self.lineEdit)
        MainWindow.setTabOrder(self.lineEdit, self.txt_solicitacao)
        MainWindow.setTabOrder(self.txt_solicitacao, self.txt_agenda)
        MainWindow.setTabOrder(self.txt_agenda, self.lineEdit_3)
        MainWindow.setTabOrder(self.lineEdit_3, self.txt_hr_inicio)
        MainWindow.setTabOrder(self.txt_hr_inicio, self.txt_hr_fim)
        MainWindow.setTabOrder(self.txt_hr_fim, self.comboBox_2)
        MainWindow.setTabOrder(self.comboBox_2, self.txt_obs)
        MainWindow.setTabOrder(self.txt_obs, self.btn_agendar)
        MainWindow.setTabOrder(self.btn_agendar, self.btn_cancelar)
        MainWindow.setTabOrder(self.btn_cancelar, self.btn_reservas)
        MainWindow.setTabOrder(self.btn_reservas, self.btn_alterarR)
        MainWindow.setTabOrder(self.btn_alterarR, self.txt_consulta_reserva)
        MainWindow.setTabOrder(self.txt_consulta_reserva, self.btn_pesquisarRsv)
        MainWindow.setTabOrder(self.btn_pesquisarRsv, self.btn_sair)
        MainWindow.setTabOrder(self.btn_sair, self.tableWidget)
        MainWindow.setTabOrder(self.tableWidget, self.lineEdit_4)
        MainWindow.setTabOrder(self.lineEdit_4, self.pushButton_2)
        MainWindow.setTabOrder(self.pushButton_2, self.btn_editar)
        MainWindow.setTabOrder(self.btn_editar, self.pushButton)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_5.setText(_translate("MainWindow", "SETOR"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Bioimagem"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Banco de Leite"))
        self.comboBox.setItemText(3, _translate("MainWindow", "Carteira Médica"))
        self.comboBox.setItemText(4, _translate("MainWindow", "Diretoria"))
        self.comboBox.setItemText(5, _translate("MainWindow", "Farmacia"))
        self.comboBox.setItemText(6, _translate("MainWindow", "Nutrição"))
        self.comboBox.setItemText(7, _translate("MainWindow", "Núcleo de Educação"))
        self.comboBox.setItemText(8, _translate("MainWindow", "Psicologia"))
        self.comboBox.setItemText(9, _translate("MainWindow", "Planejamento Estratégico"))
        self.comboBox.setItemText(10, _translate("MainWindow", "Recursos Humanos"))
        self.comboBox.setItemText(11, _translate("MainWindow", "Tecnologia da Informação"))
        self.comboBox.setItemText(12, _translate("MainWindow", "Oncologia"))
        self.comboBox.setItemText(13, _translate("MainWindow", "Outros"))
        self.label_6.setText(_translate("MainWindow", "SOLICITANTE"))
        self.label_7.setText(_translate("MainWindow", "DATA SOLICITAÇÃO"))
        self.label_8.setText(_translate("MainWindow", "DATA AGENDA"))
        self.label_4.setText(_translate("MainWindow", "RESERVA SALA DE TREINAMENTO"))
        self.label_10.setText(_translate("MainWindow", "STATUS"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "Agendado"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "Aguardando chamado"))
        self.comboBox_2.setItemText(3, _translate("MainWindow", "Aguardando confirmação"))
        self.comboBox_2.setItemText(4, _translate("MainWindow", "Cancelado"))
        self.label_9.setText(_translate("MainWindow", "HORARIO INICIO"))
        self.label_11.setText(_translate("MainWindow", "HORARIO FIM"))
        self.label_13.setText(_translate("MainWindow", "CHAMADO GLPI"))
        self.label_81.setText(_translate("MainWindow", "Número da Reserva"))
        self.btn_pesquisarRsv.setText(_translate("MainWindow", "P E S Q U I S A R"))
        self.btn_novaRsv.setText(_translate("MainWindow", "NOVO"))
        self.btn_editar.setText(_translate("MainWindow", "EDITAR"))
        self.btn_agendar.setText(_translate("MainWindow", "A G E N D A R"))
        self.btn_cancelar.setText(_translate("MainWindow", "C A N C E L A R"))
        self.label_12.setText(_translate("MainWindow", "OBSERVACÃO"))
        self.btn_reservas.setText(_translate("MainWindow", "CONSULTAR RESERVAS"))
        self.btn_sair.setText(_translate("MainWindow", "S A I R"))
        self.btn_alterarR.setText(_translate("MainWindow", "A L T E R A R "))
        self.pushButton.setText(_translate("MainWindow", "CONSULTAR"))
        self.label_2.setText(_translate("MainWindow", "Setor"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Reserva"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Setor"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Solicitante"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Data Solicitação"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Data Agenda"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Chamado"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Hora Inicio"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Hora Fim"))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "Status"))
        item = self.tableWidget.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "OBS"))
        self.label_14.setText(_translate("MainWindow", "CONSULTAR RESERVAS"))
        self.pushButton_2.setText(_translate("MainWindow", "AGENDAR"))

        # self.btn_reservas.clicked.connect(self.botaoreservas)
        self.btn_reservas.clicked.connect(self.terceiroPDF)
        self.pushButton_2.clicked.connect(self.botaovoltar)
        self.btn_sair.clicked.connect(MainWindow.close)
        self.btn_novaRsv.clicked.connect(self.InReserva)
        self.btn_agendar.clicked.connect(self.ConfReserva)
        self.btn_alterarR.clicked.connect(self.alterarReserva)
        self.btn_pesquisarRsv.clicked.connect(self.editarReserva)
        self.txt_solicitacao.setInputMask("99/99/9999")
        self.txt_agenda.setInputMask("99/99/9999")
        self.txt_hr_inicio.setInputMask("00:00")
        self.txt_hr_fim.setInputMask("00:00")
        self.pushButton.clicked.connect(self.pesquisar)
        self.btn_cancelar.clicked.connect(self.cancelarReserva)
        self.btn_editar.clicked.connect(self.modoEdicao)


    def botaoreservas(self):
            self.stackedWidget.setCurrentWidget(self.page_2)
    
    def botaovoltar(self):
            self.stackedWidget.setCurrentWidget(self.page)
    
    def InReserva(self):
            self.comboBox.setCurrentIndex(-1)
            self.lineEdit.setText("")
            self.lineEdit_3.setText("")
            self.txt_obs.setText("")
            self.comboBox_2.setCurrentIndex(-1)
            self.txt_solicitacao.setText("")
            self.txt_agenda.setText("")
            self.txt_hr_inicio.setText("")
            self.txt_hr_fim.setText("")
        #     self.dateEdit.setDateTime(QtCore.QDateTime.currentDateTime())
        #     self.dateEdit_2.setDateTime(QtCore.QDateTime.currentDateTime())
            self.comboBox.setEnabled(True)
            self.lineEdit.setEnabled(True)
            self.lineEdit_3.setEnabled(True)
            self.txt_obs.setEnabled(True)
            self.comboBox_2.setEnabled(True)
            self.txt_solicitacao.setEnabled(True)
            self.txt_agenda.setEnabled(True)
            self.txt_hr_inicio.setEnabled(True)
            self.txt_hr_fim.setEnabled(True)
            self.btn_agendar.setEnabled(True)


    def ConfReserva(self):
        
        if  not self.comboBox.currentText():
                        msg = QMessageBox()                        
                        msg.setWindowTitle("AVISO")
                        msg.setIcon(QMessageBox.Warning)
                        msg.setText("INFORME O SETOR ")
                        msg.exec()
                        # return False
           
        elif  not self.lineEdit.text():
                        msg = QMessageBox()                        
                        msg.setWindowTitle("AVISO")
                        msg.setIcon(QMessageBox.Warning)
                        msg.setText("INFORME UM SOLICITANTE ")
                        msg.exec()
                        # return False

        elif  not self.txt_solicitacao.text():
                        msg = QMessageBox()                        
                        msg.setWindowTitle("AVISO")
                        msg.setIcon(QMessageBox.Warning)
                        msg.setText("INFORME A DATA DE SOLICITAÇÃO")
                        msg.exec()
                        # return False     

        elif not self.txt_agenda.text():
                        msg = QMessageBox()
                        msg.setWindowTitle("AVISO")
                        msg.setIcon(QMessageBox.Warning)
                        msg.setText("DEFINA A DATA DA AGENDA")
                        msg.exec() 

        elif  not self.comboBox_2.currentText():
                        msg = QMessageBox()                        
                        msg.setWindowTitle("AVISO")
                        msg.setIcon(QMessageBox.Warning)
                        msg.setText("DEFINA UM STATUS ")
                        msg.exec()
                        # return False      

        else:                       

        
                setor = self.comboBox.currentText()
                solicitante = self.lineEdit.text()
                data_solicitacao = self.txt_solicitacao.text()
                data_agenda= self.txt_agenda.text()
                chamado = self.lineEdit_3.text()
                hr_inicio = self.txt_hr_inicio.text()
                hr_fim = self.txt_hr_fim.text()
                Estatus=self.comboBox_2.currentText()
                obs = self.txt_obs.text()            

                banco = sqlite3.connect('Reserva_treinamento.db')
                cursor = banco.cursor()
                cursor.execute("INSERT INTO Reserva(setor,solicitante,data_solicitacao,data_agenda,chamado,hr_inicio,hr_fim,Estatus,obs) VALUES('"+setor+"','"+solicitante+"','"+data_solicitacao+"','"+data_agenda+"','"+chamado+"'\
                        ,'"+hr_inicio+"','"+hr_fim+"','"+Estatus+"','"+obs+"')")

                banco.commit()
                banco.close()
                msg=QMessageBox()
                msg.setWindowTitle("AVISO")
                msg.setText("Reserva realizada com sucesso")
                msg.exec()

                self.comboBox.setCurrentIndex(-1)
                self.lineEdit.setText("")
                self.lineEdit_3.setText("")
                self.comboBox_2.setCurrentIndex(-1)
                self.txt_obs.setText("")
                self.txt_solicitacao.setText("")
                self.txt_agenda.setText("")
                self.txt_hr_inicio.setText("")
                self.txt_hr_fim.setText("")

                self.comboBox.setEnabled(False)
                self.lineEdit.setEnabled(False)
                self.lineEdit_3.setEnabled(False)
                self.txt_obs.setEnabled(False)
                self.comboBox_2.setEnabled(False)
                self.txt_solicitacao.setEnabled(False)
                self.txt_agenda.setEnabled(False)
                self.txt_hr_inicio.setEnabled(False)
                self.txt_hr_fim.setEnabled(False)

    def editarReserva(self):
        reserva_n = self.txt_consulta_reserva.text()
        banco = sqlite3.connect('Reserva_treinamento.db') 
        sql=( "SELECT * FROM Reserva WHERE Reserva_N LIKE '%"+(reserva_n)+"%'")
        resul = banco.execute(sql)
       
        if resul:
                
                for dt in resul: 
                        
                        self.txt_id_reserva.setText(str(dt[0]))
                        self.comboBox.setCurrentText(str(dt[1]))
                        self.lineEdit.setText(str(dt[2]))
                        self.txt_solicitacao.setText(str(dt[3]))
                        self.txt_agenda.setText(str(dt[4]))
                        self.lineEdit_3.setText(str(dt[5]))
                        self.txt_hr_inicio.setText(str(dt[6]))
                        self.txt_hr_fim.setText(str(dt[7]))
                        self.comboBox_2.setCurrentText(str(dt[8]))
                        self.txt_obs.setText(str(dt[9]))
                        self.btn_editar.setEnabled(True)

    def modoEdicao(self):
            self.comboBox.setEnabled(True)
            self.lineEdit.setEnabled(True)
            self.lineEdit_3.setEnabled(True)
            self.txt_obs.setEnabled(True)
            self.comboBox_2.setEnabled(True)
            self.txt_solicitacao.setEnabled(True)
            self.txt_agenda.setEnabled(True)
            self.txt_hr_inicio.setEnabled(True)
            self.txt_hr_fim.setEnabled(True)
            self.btn_agendar.setEnabled(False)
            self.btn_cancelar.setEnabled(True)
            self.btn_alterarR.setEnabled(True)


    def pesquisar(self):             
        setor = self.lineEdit_4.text()  
        banco = sqlite3.connect('Reserva_treinamento.db') 
        sql=( "SELECT * FROM reserva WHERE setor like '%"+str(setor)+"%' ORDER BY data_solicitacao DESC" )
        resul = banco.execute(sql)        
        self.tableWidget.setRowCount(0)
        print(resul)
        for row_number, row_data in enumerate(resul):
                self.tableWidget.insertRow(row_number)
                for colum_number, data in enumerate(row_data):
                    self.tableWidget.setItem(row_number, colum_number,
                                             QtWidgets.QTableWidgetItem(str(data)))

    def alterarReserva(self):
        global cd_reserva

        reserva_n = self.txt_id_reserva.text()
        setor = self.comboBox.currentText()
        solicitante = self.lineEdit.text()
        data_solicitacao = self.txt_solicitacao.text()
        data_agenda= self.txt_agenda.text()
        chamado = self.lineEdit_3.text()
        hr_inicio = self.txt_hr_inicio.text()
        hr_fim = self.txt_hr_fim.text()
        Estatus=self.comboBox_2.currentText()
        obs = self.txt_obs.text() 
        n_reserva_n = self.txt_id_reserva.text()   

        banco = sqlite3.connect('Reserva_treinamento.db') 
        cursor = banco.cursor()
        sql = ("UPDATE Reserva SET Setor= '{}', solicitante = '{}', data_solicitacao = '{}', data_agenda= '{}', chamado='{}', hr_inicio = '{}', hr_fim='{}',Estatus= '{}', obs='{}'\
                 WHERE  reserva_n ='{}'".format(setor,solicitante,data_solicitacao,data_agenda,chamado,hr_inicio,hr_fim,Estatus,obs ,n_reserva_n))
        
        resul = banco.execute(sql)
        reserva_n = n_reserva_n
        
        banco.commit()
        banco.close()
        msg = QMessageBox()
        msg.setWindowTitle("AVISO")
        msg.setText("Dados alterados com Sucesso")
        msg.exec()

        self.comboBox.setCurrentIndex(-1)
        self.lineEdit.setText("")
        self.lineEdit_3.setText("")
        self.comboBox_2.setCurrentIndex(-1)
        self.txt_obs.setText("")
        self.txt_solicitacao.setText("")
        self.txt_agenda.setText("")
        self.txt_hr_inicio.setText("")
        self.txt_hr_fim.setText("")

        self.comboBox.setEnabled(False)
        self.lineEdit.setEnabled(False)
        self.lineEdit_3.setEnabled(False)
        self.txt_obs.setEnabled(False)
        self.comboBox_2.setEnabled(False)
        self.txt_solicitacao.setEnabled(False)
        self.txt_agenda.setEnabled(False)
        self.txt_hr_inicio.setEnabled(False)
        self.txt_hr_fim.setEnabled(False)
        

    def cancelarReserva(self):

                self.comboBox.setCurrentIndex(-1)
                self.lineEdit.setText("")
                self.lineEdit_3.setText("")
                self.comboBox_2.setCurrentIndex(-1)
                self.txt_obs.setText("")
                self.txt_solicitacao.setText("")
                self.txt_agenda.setText("")
                self.txt_hr_inicio.setText("")
                self.txt_hr_fim.setText("")
                self.txt_id_reserva.setText("")
                self.txt_consulta_reserva.setText("")


                self.comboBox.setEnabled(False)
                self.lineEdit.setEnabled(False)
                self.lineEdit_3.setEnabled(False)
                self.txt_obs.setEnabled(False)
                self.comboBox_2.setEnabled(False)
                self.txt_solicitacao.setEnabled(False)
                self.txt_agenda.setEnabled(False)
                self.txt_hr_inicio.setEnabled(False)
                self.txt_hr_fim.setEnabled(False)
                self.btn_editar.setEnabled(False)
                self.btn_alterarR.setEnabled(False)
                self.btn_agendar.setEnabled(False)

# class relatorios():
    def printReserva(self):
                webbrowser.open("reservas.pdf")
    def printPorSetor(self):
                webbrowser.open("Reservas_setor.pdf")


    def gerarPDFF(self):
                self.c = canvas.Canvas("reservas.pdf")
                self.SetoRR = self.comboBox.currentText()
                self.SolicitantEE = self.lineEdit.text()
                self.DataSolicitacaoO = self.txt_solicitacao.text()
                self.DataAgendaA = self.txt_agenda.text()
                self.ChamadoO = self.lineEdit_3.text()
                self.HRinicio = self.txt_hr_inicio.text()
                self.HRfim = self.txt_hr_fim.text()
                self.status = self.comboBox_2.currentText()
                self.Obs = self.txt_obs.text()


                #######Cabeçalho##########
                self.c.setFont("Helvetica-Bold", 18)
                self.c.drawString(200, 730, 'Confirmação de Reserva')

                ########Corpo###############################
                self.c.setFont("Helvetica-Bold", 9)
                self.c.drawString(20, 700, 'Setor: ' + self.SetoRR )
                self.c.drawString(120, 700, 'Solicitante: ' + self.SolicitantEE)
                self.c.drawString(280, 700, 'Data da solicitação: ' + self.DataSolicitacaoO)
                self.c.drawString(430, 700, 'Data de agendamento: ' + self.DataAgendaA)
                self.c.drawString(20, 680, 'Chamado GLPI: ' + self.ChamadoO)
                self.c.drawString(120, 680, 'Horário de Inicio: ' + self.HRinicio)
                self.c.drawString(240, 680, 'Horário de Final: ' + self.HRfim)
                self.c.drawString(360, 680, 'Status: ' + self.status)
                self.c.drawString(20, 660, 'Observações: ' + self.Obs)

                # Table(self.SetoRR, colWidths=85, rowHeights=30, repeatRows=1)
                # self.c.Table(5 * [0.4 * inch], 4 * [0.4 * inch])
                # self.c.drawString(x=500, y=15, text="Página 1 / " )
                self.c.drawString(540, 28, datetime.date.today().strftime("%d/%m/%Y"))
                ###########coloca moldura nos textos#########
                self.c.rect(18,695,100,20)
                self.c.rect(18, 695,260, 20)
                self.c.rect(18, 695, 410, 20)
                self.c.rect(18, 695, 560, 20)

                self.c.rect(18, 675, 100, 20)
                self.c.rect(18, 675, 210, 20)
                self.c.rect(18, 675, 340, 20)
                self.c.rect(18, 675, 560, 20)

                self.c.rect(18, 625, 560, 50)

                # flow_obj = []
                # frame = Frame(18, 625, 560, 50, showBoundary=20)
                # frame.addFromList(flow_obj, self.c)
                ################################################
                ###########coloca imagem no PDF#################
                self.c.drawInlineImage('HEC.jpg', 100, 750, 400,80)


                
                self.c.showPage()
                self.c.save()
                self.printReserva()
    def outropdf(self):

            self.c = canvas.Canvas("reservas.pdf")
            self.c.setLineWidth(.3)
            self.c.setFont('Helvetica', 12)

            # doc = SimpleDocTemplate("test_report_lab.pdf", pagesize=A4, rightMargin=30,leftMargin=30, topMargin=30,bottomMargin=18)
            self.c.drawString(30, 750, 'COMUNICADO OFICIAL')
            self.c.drawString(30, 735, 'EMPRESAS ACME')
            self.c.drawString(500, 750, "12/12/2011")
            self.c.line(480, 747, 580, 747)
            # self.c.setLineWidth(thinline)

            self.c.drawString(275, 725, 'SALDO DEVEDOR:')
            self.c.drawString(500, 725, "R$ 1.000,00")
            self.c.line(378, 723, 580, 723)

            self.c.drawString(30, 703, 'RECEBIDO POR:')
            self.c.line(130, 700, 580, 700)
            self.c.drawString(130, 703, "JOHN DOE")
            flow_obj=[]
            # frame=Frame(20,50,50,50, showBoundary=1)
            # frame.addFromList(flow_obj,self.c)




            self.c.showPage()
            self.c.save()
            self.printReserva()

    def terceiroPDF(self):

            # reserva_n = self.txt_consulta_reserva.text()
            pdf = SimpleDocTemplate("Reservas_setor.pdf", pagesize=landscape(letter))
            flow_obj = []
            
            td = [["Setor","Solicitante","Solicitação","Agenda","GLPI","Hora_Inicio","Hora_fim","Status","obs"]]
            banco = sqlite3.connect('Reserva_treinamento.db')
            sql = ("SELECT * FROM Reserva ORDER BY setor" )
            resul = banco.execute(sql)
            data_row = resul.fetchall()
            for row in data_row:
                data = [row[1],row[2],row[3],row[4], row[5],row[6], row[7], row[8], row[9]]
                td.append(data)
            table = Table(td)
            ts=TableStyle([("GRID",(0,0),(-1,-1),2, colors.black),("BACKGROUND",(0,0),(-1,0), colors.grey)])
            table.setStyle(ts)
            flow_obj.append(table)
            pdf.build(flow_obj)
            self.printPorSetor()

               



        #     tdata =[]
        #     if resul:

        #         for dt in resul:
        #                     rowdata = []
        #                     ReservaA = self.txt_id_reserva.setText(str(dt[0]))
        #                     SetorR =self.comboBox.setCurrentText(str(dt[1]))
        #                     SolicitanteE = self.lineEdit.setText(str(dt[2]))
        #                     SolicitacaoO = self.txt_solicitacao.setText(str(dt[3]))
        #                     agendaA = self.txt_agenda.setText(str(dt[4]))
        #                     ChamadoO = self.lineEdit_3.setText(str(dt[5]))
        #                     HoraI = self.txt_hr_inicio.setText(str(dt[6]))
        #                     HoraF = self.txt_hr_fim.setText(str(dt[7]))
        #                     StatusS = self.comboBox_2.setCurrentText(str(dt[8]))
        #                     ObsS = self.txt_obs.setText(str(dt[9]))
                            
        #                     rowdata.append[ReservaA]
        #                     rowdata.append[SetorR]
        #                     rowdata.append[SolicitanteE]
        #                     rowdata.append[SolicitacaoO]
        #                     rowdata.append[ChamadoO]
        #                     rowdata.append[HoraI]
        #                     rowdata.append[HoraF]
        #                     rowdata.append[StatusS]
        #                     rowdata.append[ObsS]
        #                     tdata.append(rowdata)
        #                     print(tdata)




        
    
        

